# consul 服务端口号

server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  # consul 注册中心地址
  cloud:
    consul:
      host: 47.107.139.152
      port: 8500
      discovery:
        service-name: ${spring.application.name}

