server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RyanWuli/springcloud-config.git
          search-paths:
            - springcloud-config # 搜索目录
          username: 972698998@qq.com
          password: zxw58975
      label: master # 读取分支
# MQ 访问 5672
  rabbitmq:
    host: 47.107.139.152
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'