server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.139.152:8848 # nacos 服务注册中心
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置 sentinel dashbord 地址
        port: 8719 # 默认8719端口，如果被占用会依次+1扫描直到找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 47.107.139.152:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data_type: json
            rule_type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
