server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.129:1111 # 配置 nacos 地址(nginx 代理转发)
#        server-addr: 47.107.139.152:8848 # 配置 nacos 地址
management:
  endpoints:
    web:
      exposure:
        include: '*' # 端点暴露
